services:
  fismed_fe:
    image: fismed-fe:latest
    container_name: fismed-fe-dev
    restart: always
    deploy:
      # mode: replicated
      # replicas: 2
      # endpoint_mode: vip
      resources:
        limits:
          cpus: '0.50'
          memory: 1.5G
    ports:
      - 3000:3000
    networks:
      - fismed-network
    # healthcheck:  # Health check for service readiness
    #   test: ["CMD-SHELL", "curl -sf http://fismed-be-dev-2:8080/api/check | grep 'message'"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 5

networks:
  fismed-network:
    driver: bridge  # Default bridge network