const columns = [
  { name: "NO.", uid: "number" },
  { name: "ID", uid: "id", sortable: true },
  { name: "NAMA BARANG", uid: "item", sortable: true },
  { name: "JUMLAH BARANG", uid: "jumlah", sortable: true },
  { name: "HARGA SATUAN", uid: "harga", sortable: true },
  { name: "ACTIONS", uid: "actions" },
];

const statusOptions = [
  { name: "Paid", uid: "paid" },
  { name: "Unpaid", uid: "unpaid" },
];

const users = [
  {
    id: 1,
    item: "Tony Reichert",
    status: "paid",
    total: "25000",
    tanggal: "2021-10-10",
  },
  {
    id: 2,
    item: "Zoey Lang",
    role: "Tech Lead",
    team: "Development",
    status: "unpaid",
    age: "25",
    email: "zoey.lang@example.com",
  },
  {
    id: 3,
    item: "Foto Wanita",
    jumlah: 20,
    harga: "Rp20.000.000,-",
    role: "Sr. Dev",
    team: "Development",
    status: "paid",
    age: "22",
  },
  {
    id: 4,
    item: "William Howard",
    role: "C.M.",
    team: "Marketing",
    status: "paid",
    age: "28",
    avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    email: "william.howard@example.com",
  },
  {
    id: 5,
    item: "Kristen Copper",
    role: "S. Manager",
    team: "Sales",
    status: "paid",
    age: "24",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    email: "kristen.cooper@example.com",
  },
  {
    id: 6,
    item: "Brian Kim",
    role: "P. Manager",
    team: "Management",
    age: "29",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "brian.kim@example.com",
    status: "paid",
  },
  {
    id: 7,
    item: "Michael Hunt",
    role: "Designer",
    team: "Design",
    status: "unpaid",
    age: "27",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29027007d",
    email: "michael.hunt@example.com",
  },
  {
    id: 8,
    item: "Samantha Brooks",
    role: "HR Manager",
    team: "HR",
    status: "paid",
    age: "31",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e27027008d",
    email: "samantha.brooks@example.com",
  },
  {
    id: 9,
    item: "Frank Harrison",
    role: "F. Manager",
    team: "Finance",
    status: "paid",
    age: "33",
    avatar: "https://i.pravatar.cc/150?img=4",
    email: "frank.harrison@example.com",
  },
  {
    id: 10,
    item: "Emma Adams",
    role: "Ops Manager",
    team: "Operations",
    status: "paid",
    age: "35",
    avatar: "https://i.pravatar.cc/150?img=5",
    email: "emma.adams@example.com",
  },
  {
    id: 11,
    item: "Brandon Stevens",
    role: "Jr. Dev",
    team: "Development",
    status: "paid",
    age: "22",
    avatar: "https://i.pravatar.cc/150?img=8",
    email: "brandon.stevens@example.com",
  },
  {
    id: 12,
    item: "Megan Richards",
    role: "P. Manager",
    team: "Product",
    status: "unpaid",
    age: "28",
    avatar: "https://i.pravatar.cc/150?img=10",
    email: "megan.richards@example.com",
  },
  {
    id: 13,
    item: "Oliver Scott",
    role: "S. Manager",
    team: "Security",
    status: "paid",
    age: "37",
    avatar: "https://i.pravatar.cc/150?img=12",
    email: "oliver.scott@example.com",
  },
  {
    id: 14,
    item: "Grace Allen",
    role: "M. Specialist",
    team: "Marketing",
    status: "unpaid",
    age: "30",
    avatar: "https://i.pravatar.cc/150?img=16",
    email: "grace.allen@example.com",
  },
  {
    id: 15,
    item: "Noah Carter",
    role: "IT Specialist",
    team: "I. Technology",
    status: "unpaid",
    age: "31",
    avatar: "https://i.pravatar.cc/150?img=15",
    email: "noah.carter@example.com",
  },
  {
    id: 16,
    item: "Ava Perez",
    role: "Manager",
    team: "Sales",
    status: "unpaid",
    age: "29",
    avatar: "https://i.pravatar.cc/150?img=20",
    email: "ava.perez@example.com",
  },
  {
    id: 17,
    item: "Liam Johnson",
    role: "Data Analyst",
    team: "Analysis",
    status: "unpaid",
    age: "28",
    avatar: "https://i.pravatar.cc/150?img=33",
    email: "liam.johnson@example.com",
  },
  {
    id: 18,
    item: "Sophia Taylor",
    role: "QA Analyst",
    team: "Testing",
    status: "unpaid",
    age: "27",
    avatar: "https://i.pravatar.cc/150?img=29",
    email: "sophia.taylor@example.com",
  },
  {
    id: 19,
    item: "Lucas Harris",
    role: "Administrator",
    team: "Information Technology",
    status: "unpaid",
    age: "32",
    avatar: "https://i.pravatar.cc/150?img=50",
    email: "lucas.harris@example.com",
  },
  {
    id: 20,
    item: "Mia Robinson",
    role: "Coordinator",
    team: "Operations",
    status: "unpaid",
    age: "26",
    avatar: "https://i.pravatar.cc/150?img=45",
    email: "mia.robinson@example.com",
  },
];

export { columns, users, statusOptions };
